import type { Finding, ScanRecord } from "../types";
import type { FindingsStore as Store } from "../store";

const SEV_EMOJI: Record<string, string> = {
  critical: "🔴",
  high: "🟠",
  medium: "🟡",
  low: "🟢",
  info: "ℹ️",
};

export function exportMarkdown(store: Store): string {
  const allFindings = store.getAll();
  const active = allFindings.filter((f) => f.status !== "resolved");
  const resolved = allFindings.filter((f) => f.status === "resolved");
  const recentScans = store.getRecentScans(1);
  const lastScan = recentScans[0] as ScanRecord | undefined;

  const counts = countBySeverity(active);
  const byCategory = groupByCategory(active);

  const lines: string[] = [];

  lines.push("# WatsonSec Security Report");
  lines.push("");
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  if (lastScan) {
    lines.push(`**Last scan:** ${new Date(lastScan.startedAt).toISOString()}`);
    lines.push(`**Tools run:** ${lastScan.toolsRun.join(", ")}`);
    if (lastScan.toolsSkipped.length) {
      lines.push(`**Tools skipped** (not applicable to detected project type):** ${lastScan.toolsSkipped.join(", ")}`);
    }
  }
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|---|---|");
  for (const sev of ["critical", "high", "medium", "low", "info"] as const) {
    if (counts[sev]) {
      lines.push(`| ${SEV_EMOJI[sev]} ${capitalize(sev)} | ${counts[sev]} |`);
    }
  }
  lines.push(`| **Total active** | **${active.length}** |`);
  lines.push(`| Resolved | ${resolved.length} |`);
  lines.push("");

  for (const [category, findings] of Object.entries(byCategory)) {
    lines.push(`## ${formatCategory(category)}`);
    lines.push("");
    for (const f of findings) {
      const sev = `${SEV_EMOJI[f.severity] ?? ""} **${capitalize(f.severity)}**`;
      lines.push(`### ${sev} — \`${f.filePath}:${f.startLine}\``);
      lines.push("");
      lines.push(`**Rule:** \`${f.ruleId.join(", ")}\`  `);
      lines.push(`**Tool(s):** ${f.tool.join(", ")}  `);
      if (f.cwe) lines.push(`**CWE:** CWE-${f.cwe}  `);
      lines.push(`**Status:** ${f.status}  `);
      lines.push(`**First seen:** ${new Date(f.firstSeen).toLocaleDateString()}`);
      lines.push("");
      lines.push(f.message);
      lines.push("");
      if (f.codeSnippet) {
        lines.push("```");
        lines.push(f.codeSnippet.slice(0, 400));
        lines.push("```");
        lines.push("");
      }
    }
  }

  if (Object.keys(byCategory).length === 0) {
    lines.push("No active findings. 🎉");
    lines.push("");
  }

  lines.push("---");
  lines.push("*Report generated by [WatsonSec](https://github.com/tejgokani/watsonsec) — local-first, open-source security for AI-generated code.*");

  return lines.join("\n");
}

function countBySeverity(findings: Finding[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const f of findings) {
    counts[f.severity] = (counts[f.severity] ?? 0) + 1;
  }
  return counts;
}

function groupByCategory(findings: Finding[]): Record<string, Finding[]> {
  const groups: Record<string, Finding[]> = {};
  for (const f of findings) {
    (groups[f.category] ??= []).push(f);
  }
  // Sort each group: critical first.
  const sevRank: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
  for (const group of Object.values(groups)) {
    group.sort((a, b) => (sevRank[a.severity] ?? 5) - (sevRank[b.severity] ?? 5));
  }
  return groups;
}

function formatCategory(cat: string): string {
  return cat
    .split("-")
    .map(capitalize)
    .join(" ");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
